apiVersion: v2
name: vertical-pod-autoscaler-crd
description: A Helm chart for the Vertical Pod Autoscaler CRDs.
version: 3.1.1
appVersion: 1.2.2
home: https://github.com/giantswarm/vertical-pod-autoscaler-crd
icon: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
annotations:
  application.giantswarm.io/team: turtles
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
restrictions:
  clusterSingleton: true
